- name: find previous release directory
  find:
    path: "{{ service_directory }}"
    file_type: directory
  register: find_result

- name: remove previous release directory
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ find_result.files | map(attribute='path') | list }}"
  when: item != service_directory_target
  become: yes
