- find:
    path: "{{ service_directory }}"
    file_type: directory
  register: find_result

- file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ find_result.files | map(attribute='path') | list }}"
  when: item != service_directory_target
  become: yes
